SportsTracker/WebSite/Models/ErrorViewModel.cs
namespace WebSite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SportsTracker/WebSite/Models/Sport.cs
namespace WebSite.Models
{
    public class Sport
    {
        public string Name { get; set; }
        public string Image { get; set; }
        public int[] Points { get; set; }

        public static Sport[] GetSports() 
        {
            Sport[] sports = new Sport[3];

            Sport football = new Sport();
            football.Name = "Football";
            football.Image = "footballcarouselimage.jpg";
            football.Points = new int[1];
            football.Points[0] = 1;
            sports[0] = football;

            Sport rugby = new Sport();
            rugby.Name = "Rugby";
            rugby.Image = "rugbycarouselimage.jpg";
            rugby.Points = new int[3];
            rugby.Points[0] = 5;
            rugby.Points[1] = 2;
            rugby.Points[2] = 3;
            sports[1] = rugby;

            Sport netball = new Sport();
            netball.Name = "Netball";
            netball.Image = "netballcarouselimage.jpg";
            netball.Points = new int[1];
            netball.Points[0] = 1;
            sports[2] = netball;

            return sports;
        }
    }
}

SportsTracker/WebSite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            Sport[] sports = Sport.GetSports();

            return View(sports);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SportsTracker/WebSite/Controllers/RecordingController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class RecordingController : Controller
    {
        public IActionResult Index(string sport)
        {
            Sport[] allSports = Sport.GetSports();
            Sport activeSport = new Sport();
            for (int i = 0; i < allSports.Length; i++)
            {
                if (allSports[i].Name == sport)
                {
                    activeSport = allSports[i];
                }
            }

            return View(activeSport);
        }

        public IActionResult Share(string emailTo, string ourScore, string theirScore)
        {
            SmtpClient email = new SmtpClient("smtp.gmail.com",587);
            email.EnableSsl = true;
            email.UseDefaultCredentials = false;
            email.Credentials = new NetworkCredential("sportstracker35@gmail.com", "bytenhzdsodpkkid");
            MailMessage message = new MailMessage();
            message.From = new MailAddress("sportstracker35@gmail.com");
            message.To.Add(emailTo);
            message.Subject = "Sports Tracker game results";
            message.Body = "Here are your game details.  We scored " + ourScore + " and they scored " + theirScore;
            email.Send(message);
            return View();
        }
    }
}

SportsTracker/WebSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <!-- Carousel Slides -->
        <div class="carousel-inner">
            @for (int i = 0; i < Model.Length; i++)
            {
                var sport = Model[i];
                <div class="carousel-item @(i==0?"active":"")">
                <img src="Images/@sport.Image" alt="@sport.Name">
                <div class="carousel-caption">
                    <h3>@sport.Name</h3>
                    @Html.ActionLink("Select","Index","Recording",new {sport = Model[i].Name})
                </div>
            </div>
            }
        </div>

        <!-- Carousel Controls -->
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

SportsTracker/WebSite/Views/Recording/Index.cshtml
@{
    ViewData["Title"] = "Recording Page";
}
<script type="text/javascript">
    function AddOurScore(amount)
    {
        score = document.getElementById('ourScore');
        currentScore = score.innerText * 1;
        currentScore = currentScore + amount;
        score.innerText = currentScore;
    }

    function AddTheirScore(amount) 
    {
        score = document.getElementById('theirScore');
        currentScore = score.innerText * 1;
        currentScore = currentScore + amount;
        score.innerText = currentScore;
    }

    var counter = 0;
    var internal;
    function StartTimer()
    {
        ShowTime();
        interval=setInterval(ShowTime, 1000)
        document.getElementById("start").setAttribute("disabled","true");
        document.getElementById("stop").removeAttribute("disabled");
    }

    function StopTimer() {
        clearInterval(interval);
        document.getElementById("stop").setAttribute("disabled", "true");
        document.getElementById("restart").removeAttribute("disabled");
        document.getElementById("finish").removeAttribute("disabled");
        var currentHtml = document.getElementById("GameProgress").innerHTML;
        counter = counter - 1;
        if (currentHtml == ""){
            currentHtml = GetGameTime();
        }
        else{
            currentHtml = currentHtml + "<br/>" + GetGameTime();
        }
        document.getElementById("GameProgress").innerHTML = currentHtml;
    }

    function RestartTimer() {
        counter = 0;
        ShowTime();
        interval = setInterval(ShowTime, 1000)
        document.getElementById("stop").removeAttribute("disabled");
        document.getElementById("restart").setAttribute("disabled", "true");
        document.getElementById("finish").setAttribute("disabled", "true");
    }

    function EndTimer() {
        counter = 0;
        ShowTime();
        clearInterval(interval);
        document.getElementById("restart").setAttribute("disabled", "true");
        document.getElementById("finish").setAttribute("disabled", "true");
        document.getElementById("share").style.display = "block";
    }

    function ShowTime() {
        document.getElementById('timeOutput').innerText = GetGameTime();
        counter = counter + 1;
    }

    function GetGameTime()
    {
        var sec_num = counter; // don't forget the second param
        var hours = Math.floor(sec_num / 3600);
        var minutes = Math.floor((sec_num - (hours * 3600)) / 60);
        var seconds = sec_num - (hours * 3600) - (minutes * 60);

        if (hours < 10) { hours = "0" + hours; }
        if (minutes < 10) { minutes = "0" + minutes; }
        if (seconds < 10) { seconds = "0" + seconds; }
        return hours + ':' + minutes + ':' + seconds;
    }

    function ShareGame()
    {
        var email = document.getElementById("emailAddress").value;
        var ourScore = document.getElementById("ourScore").innerText
        var theirScore = document.getElementById("theirScore").innerText;
        var url = "/Recording/Share?emailTo="+email+"&ourScore="+ourScore+"&theirScore="+theirScore;
        location.href = url;
    }
</script>

<div class="heading">
<h1>@Model.Name recording</h1>
</div>

<div class="scoring">
    <div class="ourScore">
        <h2>Our Score</h2>
        <h3 id="ourScore" class="OurScore">0</h3>
        @for (int i = 0; i < Model.Points.Length; i++)
        {
            <input type="button" onclick="AddOurScore(@Model.Points[i])" class="OurScore" value="@(Model.Points[i])" />
        }
    </div>

    <div class="theirScore">
        <h2>Their Score</h2>
        <h3 id="theirScore" class="TheirScore">0</h3>
        @for (int i = 0; i < Model.Points.Length; i++)
        {
            <input type="button" onclick="AddTheirScore(@Model.Points[i])" class="TheirScore" value="@(Model.Points[i])" />
        }
    </div>
</div>

<div class="box">
    <div class="timer">
        <h4>Current game time:</h4><p id="timeOutput"></p>
        <h4>Ongoing game time progress: </h4><p id="GameProgress"></p>
        <input id="start" type="button" class="btnStartTimer" onclick="StartTimer()" value="Start Game" />
        <input id="stop" type="button" class="btnStopTimer" onclick="StopTimer()" disabled value="Pause/Stop Game (end period)" />
        <input id="restart" type="button" class="btnRestartTimer" onclick="RestartTimer()" disabled value="Restart Timer" />
        <input id="finish" type="button" class="btnEndTimer" onclick="EndTimer()" disabled value="Finish Game" />
    </div>
</div>
<div class="box">
    <div id="share" style="display:none">
        <h4>Enter email address to send game:</h4>
        <input type="email" id="emailAddress" />
        <input type="button" class="btnShare" onclick="ShareGame()" value="Share Game"/>
    </div>
</div>

SportsTracker/WebSite/Views/Recording/Share.cshtml
@{
    ViewData["Title"] = "Shared Page";
}
<h2>Your game detaiils have been emailed to the email address entered.</h2>

SportsTracker/WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ASHS Sports Tracker</title>
    <link rel="stylesheet" href="/css/site.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">ASHS Sports Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/Home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Recording">Recording</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <img src="/Images/navbarlogoimage.png" alt="Navigation Bar ASHS Logo" class="top-left-image">
    @RenderBody()
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>